"""
Generates synthetic exemplar datasets for the case-study notebooks.

Design principle: each dataset is the deterministic output of a documented
forward model with a documented seed. Notebooks pretend not to know the
generating parameters and try to recover them. This gives full
reproducibility (no external network dependencies) plus an honest
identifiability story (the truth is known, so estimator bias and
confidence intervals can be checked).

Run from /tmp/hyman2026essential/ (or any CWD):
    python data/_generate_synthetic.py
"""
import json
import os
import sys
from pathlib import Path

import numpy as np
from scipy.integrate import odeint

ROOT = Path(__file__).resolve().parent
COVID = ROOT / "covid"
DENGUE = ROOT / "dengue"
HIV = ROOT / "hiv"

# Make repo importable for notebook-style import paths
sys.path.insert(0, str(ROOT.parent / "python"))


def _save_csv(path: Path, header: list[str], rows: list[list]):
    with open(path, "w") as f:
        f.write(",".join(header) + "\n")
        for row in rows:
            f.write(",".join(str(x) for x in row) + "\n")


def _save_json(path: Path, obj: dict):
    with open(path, "w") as f:
        json.dump(obj, f, indent=2)


# ============================================================================
# COVID-19: synthetic early-pandemic incidence (90 days, daily reported cases)
# ============================================================================

def gen_covid():
    np.random.seed(20260507)  # documented seed

    # Truth (notebooks pretend not to know these)
    c_I, beta = 14.0, 0.04
    tau_E, tau_R = 4.0, 5.0
    rho = 0.4  # reporting fraction
    N = 1.0e7
    I0 = 5_000.0
    E0 = 5_000.0
    S0 = N - E0 - I0

    def seir(y, t):
        S, E, I, R = y
        inc = c_I * beta * S * I / N
        return [-inc, inc - E/tau_E, E/tau_E - I/tau_R, I/tau_R]

    t = np.linspace(0, 90, 91)
    y0 = [S0, E0, I0, 0.0]
    sol = odeint(seir, y0, t)
    S, E, I, R = sol.T
    new_inf = -np.diff(np.concatenate([[S0], S]))   # daily new infections

    # Reporting model: Poisson with mean = rho * new_inf
    reported = np.random.poisson(rho * new_inf)

    # Save: dates as integer day index (notebooks add real dates if desired)
    rows = [[int(d), int(c)] for d, c in zip(t.astype(int), reported)]
    _save_csv(COVID / "metro_daily_cases.csv", ["day", "reported_cases"], rows)

    metadata = {
        "title": "Synthetic COVID-19 daily reported cases, illustrative metro area",
        "n_days": 91,
        "population_N": N,
        "generating_model": "SEIR with reporting fraction rho",
        "generating_parameters_TRUTH_FOR_NOTEBOOK_VERIFICATION": {
            "c_I": c_I, "beta": beta, "tau_E": tau_E, "tau_R": tau_R, "rho": rho,
            "S0": S0, "E0": E0, "I0": I0,
            "R0_basic": c_I * beta * tau_R,
        },
        "noise_model": "Poisson(rho * new_infections_per_day)",
        "seed": 20260507,
        "purpose": "Used by Chapter 15 notebooks to demonstrate early-pandemic "
                   "R_0 estimation, R_e(t) reconstruction, and under-reporting correction. "
                   "Notebooks fit without knowing the truth; the truth is here for verification only.",
    }
    _save_json(COVID / "metadata.json", metadata)

    with open(COVID / "source_attribution.md", "w") as f:
        f.write(
            "# Synthetic COVID-19 dataset\n\n"
            "**Type:** Synthetic, generated by `data/_generate_synthetic.py`.\n\n"
            "**License:** [CC BY-NC 4.0](../../LICENSE-CONTENT)\n\n"
            "**Purpose:** Pedagogical exemplar for the Chapter 15 case-study notebooks. "
            "Generating parameters are documented in `metadata.json` for verification "
            "purposes; notebooks treat the data as if unknown and attempt to recover them.\n\n"
            "**Seed:** 20260507\n\n"
            "**Real data alternatives:** For analysis with actual COVID-19 data, see "
            "Our World in Data (https://github.com/owid/covid-19-data) or the JHU CSSE "
            "COVID-19 Data Repository.\n"
        )
    print(f"  wrote: data/covid/  ({3} files)")


# ============================================================================
# Dengue: synthetic 5-year monthly incidence with strong seasonality
# ============================================================================

def gen_dengue():
    np.random.seed(20260508)

    a = 0.4
    b = 0.4
    c = 0.4
    mu_v_baseline = 1.0/14.0
    mu_v_amp = 0.5
    gamma_h = 1.0/7.0
    xi_h = 1.0/(2.0*365.0)         # 2-year mean immunity (cross-serotype dynamics simplification)
    M_over_N = 5.0
    N_h = 1.0  # normalized

    def vh(y, t):
        SH, IH, RH, SV, IV = y
        # Phase pi -> mu_v MIN in middle of year (rainy season -> low vector mortality)
        mu_v = mu_v_baseline * (1 + mu_v_amp * np.cos(2*np.pi*t/365 + np.pi))
        Lam_h = a * b * M_over_N * IV
        Lam_v = a * c * IH
        return [-Lam_h*SH + xi_h*RH,
                Lam_h*SH - gamma_h*IH,
                gamma_h*IH - xi_h*RH,
                mu_v*(1-SV) - Lam_v*SV,
                Lam_v*SV - mu_v*IV]

    t = np.linspace(0, 365*5, 365*5+1)
    y0 = [0.95, 0.001, 0.049, 1.0, 0.0]
    sol = odeint(vh, y0, t)
    SH, IH, RH, SV, IV = sol.T
    new_inf = a * b * M_over_N * IV * SH
    new_inf = np.maximum(new_inf, 0.0)  # clip numerical noise

    # Aggregate to monthly counts (per 100K population)
    pop_per_100k = 100_000
    monthly_idx = np.arange(0, 365*5+1, 30)
    rows = []
    for i in range(len(monthly_idx)-1):
        lo, hi = monthly_idx[i], monthly_idx[i+1]
        cumulative = max(0.0, float(new_inf[lo:hi].sum() * pop_per_100k))
        observed = int(np.random.poisson(cumulative))
        rows.append([i+1, observed])

    _save_csv(DENGUE / "monthly_cases_per_100k.csv",
              ["month_index", "cases_per_100k"], rows)

    metadata = {
        "title": "Synthetic dengue monthly cases per 100K, illustrative tropical city",
        "duration_months": len(rows),
        "population_basis": pop_per_100k,
        "generating_model": "vector-host SIRS with seasonal vector mortality + 2-year waning immunity",
        "generating_parameters_TRUTH_FOR_NOTEBOOK_VERIFICATION": {
            "a": a, "b": b, "c": c,
            "mu_v_baseline": mu_v_baseline, "mu_v_amplitude": mu_v_amp,
            "gamma_h": gamma_h, "xi_h": xi_h, "M_over_N": M_over_N,
            "seasonal_phase_radians": "pi (mu_v minimum in mid-year, simulating wet season)",
        },
        "noise_model": "Poisson(monthly cumulative incidence per 100K)",
        "seed": 20260508,
        "purpose": "Used by Chapter 16 notebooks to demonstrate seasonal-R_0 calibration "
                   "and intervention-sensitivity analysis. Notebooks fit without knowing the truth.",
    }
    _save_json(DENGUE / "metadata.json", metadata)

    with open(DENGUE / "source_attribution.md", "w") as f:
        f.write(
            "# Synthetic dengue dataset\n\n"
            "**Type:** Synthetic, generated by `data/_generate_synthetic.py`.\n\n"
            "**License:** [CC BY-NC 4.0](../../LICENSE-CONTENT)\n\n"
            "**Purpose:** Pedagogical exemplar for the Chapter 16 case-study notebooks.\n\n"
            "**Seed:** 20260508\n\n"
            "**Real data alternatives:** WHO Dengue surveillance data; PAHO Dengue "
            "case data for the Americas.\n"
        )
    print(f"  wrote: data/dengue/  ({3} files)")


# ============================================================================
# HIV: synthetic 30-year prevalence trajectory with two-period treatment rollout
# ============================================================================

def gen_hiv():
    np.random.seed(20260509)

    NM = NF = 0.5
    cMF = cFM = 1.5
    betaMF, betaFM = 0.20, 0.10
    tau_R = 10.0
    tau_R_treated = 0.5
    NU = 1  # normalized total population

    # Treatment coverage: zero before year 10, ramps to 60% by year 25
    def cov(t):
        if t < 10: return 0.0
        if t > 25: return 0.6
        return 0.6 * (t - 10) / 15.0

    def hiv_rhs(y, t):
        SM, IM, TM, SF, IF, TF = y
        c_eff = cov(t)
        # Effective infectious duration for untreated
        # Combined infectious load from group g: IM + TM*(tau_R_treated/tau_R) -- treated less infectious
        eff_M = IM + TM * (tau_R_treated/tau_R)
        eff_F = IF + TF * (tau_R_treated/tau_R)
        inc_M = betaMF * cMF * SM * eff_F / NF
        inc_F = betaFM * cFM * SF * eff_M / NM
        # Untreated -> treated at rate proportional to coverage
        rate_to_tx = c_eff / 2.0  # half-life 2 years to reach treatment when coverage active
        # Recovery (death from disease) at rate 1/tau_R for untreated
        return [-inc_M,
                inc_M - IM/tau_R - rate_to_tx*IM,
                rate_to_tx*IM - TM/tau_R_treated/2,  # treated stay alive longer
                -inc_F,
                inc_F - IF/tau_R - rate_to_tx*IF,
                rate_to_tx*IF - TF/tau_R_treated/2]

    t = np.linspace(0, 30, 361)  # monthly for 30 years
    y0 = [0.495, 0.005, 0.0, 0.495, 0.005, 0.0]
    sol = odeint(hiv_rhs, y0, t)
    SM, IM, TM, SF, IF, TF = sol.T

    prev_M = (IM + TM) / NM
    prev_F = (IF + TF) / NF
    overall = ((IM+TM) + (IF+TF)) / 1.0

    # Annual snapshots with multiplicative log-normal noise (surveillance estimates)
    annual_idx = np.arange(0, 361, 12)
    rows = []
    for i in annual_idx:
        year = float(t[i])
        # Multiplicative noise sigma=0.05 reflects survey-based prevalence uncertainty
        noise_M = np.exp(np.random.normal(0, 0.05))
        noise_F = np.exp(np.random.normal(0, 0.05))
        rows.append([round(year, 1),
                     round(float(prev_M[i] * noise_M), 5),
                     round(float(prev_F[i] * noise_F), 5),
                     round(float(cov(year)), 3)])

    _save_csv(HIV / "annual_prevalence_with_treatment.csv",
              ["year", "prevalence_M", "prevalence_F", "treatment_coverage"], rows)

    metadata = {
        "title": "Synthetic HIV bipartite prevalence, illustrative generalized epidemic with TasP rollout",
        "duration_years": 30,
        "generating_model": "bipartite (M-F) SI model with treatment-as-prevention compartment "
                           "and time-varying treatment coverage",
        "generating_parameters_TRUTH_FOR_NOTEBOOK_VERIFICATION": {
            "NM": NM, "NF": NF, "cMF": cMF, "cFM": cFM,
            "betaMF": betaMF, "betaFM": betaFM,
            "tau_R_untreated_years": tau_R,
            "tau_R_treated_years": tau_R_treated,
            "treatment_rollout_start_year": 10,
            "treatment_rollout_end_year": 25,
            "treatment_coverage_max": 0.6,
            "R0_untreated": 2.12,
        },
        "noise_model": "log-normal multiplicative noise with sigma=0.05 (survey-based prevalence estimates)",
        "seed": 20260509,
        "purpose": "Used by Chapter 17 notebooks to demonstrate HIV bipartite calibration, "
                   "treatment-as-prevention impact, and geographic-comparison structure.",
    }
    _save_json(HIV / "metadata.json", metadata)

    with open(HIV / "source_attribution.md", "w") as f:
        f.write(
            "# Synthetic HIV dataset\n\n"
            "**Type:** Synthetic, generated by `data/_generate_synthetic.py`.\n\n"
            "**License:** [CC BY-NC 4.0](../../LICENSE-CONTENT)\n\n"
            "**Purpose:** Pedagogical exemplar for the Chapter 17 case-study notebooks.\n\n"
            "**Seed:** 20260509\n\n"
            "**Real data alternatives:** UNAIDS AIDSinfo "
            "(https://aidsinfo.unaids.org); the DHS Program "
            "(https://dhsprogram.com) for survey-based prevalence.\n"
        )
    print(f"  wrote: data/hiv/  ({3} files)")


if __name__ == "__main__":
    print("Generating synthetic exemplar datasets...")
    gen_covid()
    gen_dengue()
    gen_hiv()
    print("Done.")
